# Generated by Django 6.0 on 2026-01-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('file', models.FileField(upload_to='casts/works/', verbose_name='ファイル')),
                ('media_type', models.CharField(choices=[('VIDEO', '動画'), ('IMAGE', '画像')], default='IMAGE', max_length=10, verbose_name='メディアタイプ')),
                ('cover_image', models.ImageField(blank=True, help_text='動画の場合のみ設定してください', null=True, upload_to='casts/covers/', verbose_name='サムネイル画像')),
                ('order', models.IntegerField(default=0, help_text='数字が小さいほど先に表示されます', verbose_name='表示順序')),
            ],
            options={
                'verbose_name': 'キャスト作品（メディア）',
                'verbose_name_plural': 'キャスト作品一覧',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CastProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='キャスト名')),
                ('tags', models.JSONField(blank=True, default=list, help_text="タグをリスト形式で入力してください。例: ['癒し', 'イケボ', 'ロールプレイ']", verbose_name='特徴タグ')),
                ('intro', models.TextField(blank=True, verbose_name='自己紹介文')),
                ('avatar', models.ImageField(upload_to='casts/avatars/', verbose_name='プロフィール画像')),
                ('saas_resource_id', models.CharField(blank=True, max_length=64, unique=True, verbose_name='SaaSリソースID')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍中')),
            ],
            options={
                'verbose_name': 'キャストプロフィール',
                'verbose_name_plural': 'キャストプロフィール一覧',
            },
        ),
    ]
