# Generated by Django 6.0 on 2026-01-05 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='castprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cast_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='castmedia',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='casts.castprofile'),
        ),
    ]
