# Generated by Django 6.0 on 2026-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmedia',
            name='file',
        ),
        migrations.AddField(
            model_name='castmedia',
            name='image_file',
            field=models.ImageField(blank=True, help_text='タイプが『画像』の場合にアップロード', null=True, upload_to='casts/works/', verbose_name='画像ファイル'),
        ),
        migrations.AddField(
            model_name='castmedia',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='タイプが『動画』の場合にURLを入力 (例: https://youtu.be/...)', null=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='castmedia',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='動画の表紙画像（未設定可）', null=True, upload_to='casts/covers/', verbose_name='サムネイル画像'),
        ),
        migrations.AlterField(
            model_name='castmedia',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', '動画 (YouTube)'), ('IMAGE', '画像')], default='IMAGE', max_length=10, verbose_name='メディアタイプ'),
        ),
        migrations.AlterField(
            model_name='castprofile',
            name='intro',
            field=models.TextField(blank=True, help_text='改行や特殊文字もそのまま保存されます。', verbose_name='自己紹介文'),
        ),
    ]
