# Generated by Django 6.0 on 2026-01-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0003_remove_castmedia_file_castmedia_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='必ずダブルクォート(")を使用してください。例: ["癒し", "イケボ", "ロールプレイ"]', verbose_name='特徴タグ'),
        ),
    ]
