# Generated by Django 6.0 on 2026-01-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0004_alter_castprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='castprofile',
            name='allow_120_min',
            field=models.BooleanField(default=False, verbose_name='Allow 120 min'),
        ),
        migrations.AddField(
            model_name='castprofile',
            name='allow_30_min',
            field=models.BooleanField(default=False, verbose_name='Allow 30 min'),
        ),
        migrations.AddField(
            model_name='castprofile',
            name='allow_60_min',
            field=models.BooleanField(default=True, verbose_name='Allow 60 min'),
        ),
    ]
