# Generated by Django 6.0 on 2026-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0005_castprofile_allow_120_min_castprofile_allow_30_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmedia',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='castprofile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='プロフィールのメイン動画 (例: https://youtu.be/...)', null=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='castmedia',
            name='image_file',
            field=models.ImageField(default='', upload_to='casts/works/', verbose_name='画像ファイル'),
            preserve_default=False,
        ),
    ]
