# Generated by Django 6.0 on 2026-01-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0006_remove_castmedia_youtube_url_castprofile_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castprofile',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'キャストプロフィール', 'verbose_name_plural': 'キャストプロフィール一覧'},
        ),
        migrations.AddField(
            model_name='castprofile',
            name='display_order',
            field=models.IntegerField(default=0, help_text='一覧ページでの表示順 (数字が小さい方が先頭)', verbose_name='表示順序'),
        ),
    ]
