# Generated by Django 6.0 on 2026-01-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0007_alter_castprofile_options_castprofile_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castprofile',
            name='saas_resource_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SaaSリソースID'),
        ),
    ]
