# Generated by Django 6.0 on 2026-01-06 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='終了時間')),
                ('is_booked', models.BooleanField(default=False, verbose_name='予約済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'シフト・空き枠',
                'verbose_name_plural': 'シフト・空き枠一覧',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, help_text='System A側のCastProfile IDなど', max_length=100, null=True, verbose_name='外部システムID')),
                ('name', models.CharField(max_length=100, verbose_name='リソース名')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
