# Generated by Django 6.0 on 2026-01-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, help_text='予約・キャンセル通知の送信先', max_length=254, null=True, verbose_name='メールアドレス'),
        ),
    ]
