# Generated by Django 6.0 on 2026-01-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='周期フラグ'),
        ),
    ]
