# Generated by Django 6.0 on 2026-01-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_recurringpattern'),
        ('tenants', '0002_tenant_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmation'), ('BOOKING_CANCELLED', 'Booking Cancellation'), ('BOOKING_REMINDER', 'Booking Reminder')], max_length=50)),
                ('subject_template', models.CharField(default='【予約確定】{{ resource_name }} との予約が確定しました', max_length=255)),
                ('body_html', models.TextField(default='<p>Default content...</p>')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'event_type')},
            },
        ),
    ]
