# Generated by Django 6.0 on 2026-01-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body_html',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='button_link',
            field=models.CharField(default='https://vr-veludo.com/my-page', help_text='按钮跳转链接', max_length=255),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='button_text',
            field=models.CharField(default='詳細を見る', help_text='按钮上的文字', max_length=50),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='email_greeting',
            field=models.TextField(default='以下の内容で予約を承りました。', help_text='开场问候语'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='email_title',
            field=models.CharField(default='予約が確定しました。', help_text='邮件的大标题', max_length=200),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='footer_text',
            field=models.TextField(default='ご予約の変更やキャンセルは 1日 前までにお願いいたします。', help_text='页脚正文'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='footer_title',
            field=models.CharField(default='当社のキャンセルポリシー', help_text='页脚标题', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='event_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmation'), ('BOOKING_CANCELLED', 'Booking Cancellation')], max_length=50),
        ),
    ]
