# Generated by Django 6.0 on 2026-01-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_emailtemplate_body_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='logo',
            field=models.ImageField(blank=True, help_text='品牌Logo', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='service_name',
            field=models.CharField(default='60分VRASMR施術コース (PCVR)', help_text='服务/菜单名称', max_length=200),
        ),
    ]
