# Generated by Django 6.0 on 2026-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_emailtemplate_logo_emailtemplate_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='send_to_cast',
            field=models.BooleanField(default=True, help_text='担当キャストにメール送る'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='send_to_customer',
            field=models.BooleanField(default=True, help_text='お客様にメール送る'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='service_name',
            field=models.CharField(default='60分VRASMR施術コース (PCVR)', help_text='サービス名', max_length=200),
        ),
    ]
