# Generated by Django 6.0 on 2026-02-09 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_emailtemplate_send_to_cast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('week_config', models.JSONField(verbose_name='設定データ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='resources.resource')),
            ],
            options={
                'verbose_name': 'シフトテンプレート',
                'verbose_name_plural': 'シフトテンプレート一覧',
                'ordering': ['-created_at'],
                'unique_together': {('resource', 'name')},
            },
        ),
    ]
