# Generated by Django 6.0 on 2026-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_resourceprofile_resourcemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepreset',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='servicepreset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='価格'),
        ),
    ]
