# Generated by Django 6.0 on 2026-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー一覧'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='アイコン'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, help_text='例: user#1234', max_length=50, null=True, verbose_name='Discord ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, help_text='例: @username', max_length=50, null=True, verbose_name='X (Twitter) ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_cast',
            field=models.BooleanField(default=False, help_text='このユーザーがキャストかどうか', verbose_name='Castフラグ'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
