# Generated by Django 6.0 on 2026-01-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_user_avatar_user_discord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vrc_id',
            field=models.CharField(blank=True, help_text='VRChat上の表示名', max_length=100, null=True, verbose_name='VRCID'),
        ),
    ]
