# Generated by Django 6.0 on 2026-01-21 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_vrc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_PAGE', 'View Page'), ('CLICK_CAST', 'Click Cast'), ('FILTER_ROLE', 'Filter Role'), ('VIEW_TAB', 'Switch Tab'), ('VIEW_SHIFT', 'Check Schedule'), ('LOGIN', 'User Login')], max_length=50, verbose_name='操作タイプ')),
                ('target', models.CharField(blank=True, help_text='例: Cast名, ページ名', max_length=100, null=True, verbose_name='ターゲット')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーアクティビティ',
                'verbose_name_plural': 'アクティビティログ',
                'ordering': ['-timestamp'],
            },
        ),
    ]
