# Generated by Django 6.0 on 2026-01-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'ユーザー履歴', 'verbose_name_plural': 'アクティビティログ'},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('VIEW_PAGE', 'View Page'), ('CLICK_CAST', 'Click Cast'), ('CLICK_SOCIAL', 'Click SNS/Video'), ('CLICK_RESERVATION', 'Click Reserve'), ('CLICK_LINK', 'Click Link'), ('OPEN_MENU', 'Open Mobile Menu'), ('FILTER_ROLE', 'Filter Role'), ('VIEW_TAB', 'Switch Tab'), ('VIEW_SHIFT', 'Check Schedule'), ('LOGIN', 'User Login'), ('BOOKING_SUCCESS', 'Booking Success'), ('SWITCH_MODE', 'Switch Mode')], max_length=50, verbose_name='操作タイプ'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='target',
            field=models.CharField(blank=True, help_text='例: Cast名, ページ名', max_length=255, null=True, verbose_name='ターゲット'),
        ),
    ]
