# Generated by Django 6.0 on 2026-03-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_useractivity_options_alter_useractivity_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('VIEW_PAGE', 'View Page'), ('CLICK_CAST', 'Click Cast'), ('CLICK_SOCIAL', 'Click SNS/Video'), ('CLICK_RESERVATION', 'Click Reserve'), ('CLICK_LINK', 'Click Link'), ('OPEN_MENU', 'Open Mobile Menu'), ('FILTER_ROLE', 'Filter Role'), ('VIEW_TAB', 'Switch Tab'), ('VIEW_SHIFT', 'Check Schedule'), ('LOGIN', 'User Login'), ('BOOKING_SUCCESS', 'Booking Success'), ('SWITCH_MODE', 'Switch Mode'), ('PAGE_DURATION', 'Page Duration')], max_length=50, verbose_name='操作タイプ'),
        ),
    ]
