# Generated by Django 6.0 on 2026-03-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_useractivity_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP')),
                ('reason', models.CharField(default='High-frequency bot traffic', max_length=255, verbose_name='理由')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='検知回数')),
                ('first_detected_at', models.DateTimeField(auto_now_add=True, verbose_name='初回検知')),
                ('last_detected_at', models.DateTimeField(auto_now=True, verbose_name='最終検知')),
                ('banned_until', models.DateTimeField(blank=True, null=True, verbose_name='解除日時')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-last_detected_at'],
            },
        ),
    ]
