"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g5=!76&2zgtur67bm0o=ilt^obkl^3!j*gs4649&bsliu_ulj7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Allauth App
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.discord', # Discord 提供商
    
    'rest_framework', # 用于API
    'corsheaders',    # 用于跨域
    'core',           # 你的用户App
    'casts',          # 你的展示App
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'veludo_db'),
        'USER': os.environ.get('DB_USER', 'dev_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'dev_password'),
        # 👇 关键：优先读取环境变量 DB_HOST，读不到才用 localhost
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True


# Static files
AUTH_USER_MODEL = 'core.User'

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- SaaS 配置 ---
SAAS_API_URL = 'http://127.0.0.1:8001/api/v1/integration'
SAAS_API_KEY = 'veludo_secret_key_123'

SESSION_COOKIE_NAME = 'veludo_sessionid'
CSRF_COOKIE_NAME = 'veludo_csrftoken'

SITE_ID = 1

# 认证后端设置
AUTHENTICATION_BACKENDS = [
    # 👇 建议保留这个，否则普通管理员无法登录 Admin 后台
    'django.contrib.auth.backends.ModelBackend',
    # Allauth 专用后端
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ==========================================
# Allauth 配置 (已修复冲突)
# ==========================================

# 1. 跳转链接
LOGIN_REDIRECT_URL = 'profile'  # 登录成功后跳转
ACCOUNT_LOGOUT_REDIRECT_URL = 'index' # 登出后跳转

# 2. 核心认证逻辑
# 允许用户同时使用 用户名 或 邮箱 登录
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
# 必须要有邮箱 (SocialAccount会自动填充)
ACCOUNT_EMAIL_REQUIRED = True
# 必须要有用户名
ACCOUNT_USERNAME_REQUIRED = True

# 3. 验证与注册行为
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 开发环境不发强制验证邮件
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True     # 👈 关键：设为 True，跳过中间的注册确认表单，避免报错
SOCIALACCOUNT_QUERY_EMAIL = True     # 👈 关键：向 Discord 请求邮箱

# 4. 自定义适配器 (保留你的逻辑)
SOCIALACCOUNT_ADAPTER = 'core.adapters.MySocialAccountAdapter' 

# 5. Discord API 设置
SOCIALACCOUNT_PROVIDERS = {
    'discord': {
        # 请求 id 和 email
        'SCOPE': ['identify'],
        'AUTH_PARAMS': {'prompt': 'none'},
        'VERIFIED_EMAIL': True,
    }
}