from django.urls import path
from .views import (
    TenantDashboardView,
    DashboardLoginView,
    DashboardSuperAdminLoginView,
    DashboardSuperGlobalView,
    DashboardRegisterShopRedirectView,
    DashboardShopSignupFormView,
    DashboardInviteAcceptView,
    DashboardTermsView,
    DashboardTokushohoView,
    DashboardPublicBookingView,
    DashboardPublicBookingAvailabilityApi,
    DashboardPublicBookingCreateApi,
    DashboardPublicBookingDetailView,
    DashboardPublicBookingCancelApi,
    DashboardPublicBookingReportApi,
    DashboardAdminReportNotificationsApi,
    DashboardTrackingApi,
    StripeWebhookView,
    dashboard_logout,
)
from .schedule_views import (
    DashboardScheduleAvailabilityApi,
    DashboardBookingActionApi,
    DashboardBookingReportApi,
    DashboardScheduleEventsApi,
    DashboardScheduleRecurringConfigApi,
    DashboardScheduleTemplateApi,
)

urlpatterns = [
    path('login/', DashboardLoginView.as_view(), name='dashboard_login'),
    path('super/login/', DashboardSuperAdminLoginView.as_view(), name='dashboard_super_login'),
    path('super/global/', DashboardSuperGlobalView.as_view(), name='dashboard_super_global'),
    path('register-shop/', DashboardRegisterShopRedirectView.as_view(), name='dashboard_register_shop'),
    path('register-shop/form/', DashboardShopSignupFormView.as_view(), name='dashboard_register_shop_form'),
    path('invite/<str:token>/', DashboardInviteAcceptView.as_view(), name='dashboard_invite_accept'),
    path('terms/', DashboardTermsView.as_view(), name='dashboard_terms'),
    path('tokushoho/', DashboardTokushohoView.as_view(), name='dashboard_tokushoho'),
    path('book/<slug:tenant_slug>/', DashboardPublicBookingView.as_view(), name='dashboard_public_booking'),
    path('book/<slug:tenant_slug>/api/availability/', DashboardPublicBookingAvailabilityApi.as_view(), name='dashboard_public_booking_availability'),
    path('book/<slug:tenant_slug>/api/create/', DashboardPublicBookingCreateApi.as_view(), name='dashboard_public_booking_create'),
    path('api/track/', DashboardTrackingApi.as_view(), name='dashboard_tracking'),
    path('webhooks/stripe/', StripeWebhookView.as_view(), name='dashboard_stripe_webhook'),
    path('book/detail/<str:access_token>/', DashboardPublicBookingDetailView.as_view(), name='dashboard_public_booking_detail'),
    path('book/detail/<str:access_token>/cancel/', DashboardPublicBookingCancelApi.as_view(), name='dashboard_public_booking_cancel'),
    path('book/detail/<str:access_token>/report/', DashboardPublicBookingReportApi.as_view(), name='dashboard_public_booking_report'),

    # 2. 登出
    path('logout/', dashboard_logout, name='logout'),

    path('', TenantDashboardView.as_view(), name='tenant_dashboard'),
    path('api/schedule/events/', DashboardScheduleEventsApi.as_view(), name='dashboard_schedule_events'),
    path('api/schedule/availability/', DashboardScheduleAvailabilityApi.as_view(), name='dashboard_schedule_availability'),
    path('api/schedule/recurring-config/', DashboardScheduleRecurringConfigApi.as_view(), name='dashboard_schedule_recurring_config'),
    path('api/schedule/templates/', DashboardScheduleTemplateApi.as_view(), name='dashboard_schedule_templates'),
    path('api/bookings/<uuid:booking_id>/', DashboardBookingActionApi.as_view(), name='dashboard_booking_action'),
    path('api/bookings/<uuid:booking_id>/report/', DashboardBookingReportApi.as_view(), name='dashboard_booking_report'),
    path('api/reports/notifications/', DashboardAdminReportNotificationsApi.as_view(), name='dashboard_admin_report_notifications'),
]
