# Generated by Django 6.0 on 2026-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='预定成功后，系统会向此地址发送 POST 请求', null=True),
        ),
    ]
