# Generated by Django 6.0 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasuser",
            name="discord_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
