# Generated by Django 6.0 on 2026-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_api_ban_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saasuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', '店铺管理员'), ('STAFF', '员工/Cast'), ('CONSUMER', 'A端用户')], default='STAFF'),
        ),
    ]
